# -*- coding:utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from Fangfull.model.m_Album import Album
from Fangfull.model.m_Song import Song
from Fangfull.model.m_Message_data import Message_data
from Fangfull.model.m_Message_res import Message_res
from Fangfull.model.m_Content_sql import Content_sql
from Fangfull.model.m_Content_url import Content_url
from Fangfull.model.m_Res_requests import Res_requests
from Fangfull.model.m_Res_data import Res_data
from Fangfull.model.m_Res_data_value import Res_data_value
